version: "3"

services:

  host_cmd_from_docker:
    image: "node:14-alpine"
    container_name: host_cmd_from_docker
    user: 1000:1000
    working_dir: "/api"
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/api:rw,Z
